In [1]:
import pandas as pd

In [2]:
file_path = './昆仑健康_核保指引_20230522.xlsx'
excel_data = pd.ExcelFile(file_path)

In [3]:
excel_data.sheet_names

['呼吸',
 '肺结节',
 '甲状腺癌',
 '甲状腺疾病',
 '血压高',
 '心血管疾病',
 '肠道',
 '胆囊',
 '肝脏',
 '上消',
 '消化系统其他',
 '妇科肿物',
 '子宫',
 '宫颈',
 '阴道',
 '乳腺',
 '血液系统',
 '泌尿',
 '外科',
 '五官科',
 '感染',
 '神经系统',
 '新生儿',
 '风湿免疫内分泌']

In [18]:
sheet_name = "妇科肿物"
sheet_data = pd.read_excel(excel_data, sheet_name=sheet_name,keep_default_na=False)

In [19]:
sheet_data.columns

Index(['疾病', 'Unnamed: 1', '资料', '检查结果', 'Unnamed: 4', '重疾', '防癌', '意外险',
       '护理险', '医疗险'],
      dtype='object')

In [26]:
have_value = ""
for idx,row in sheet_data.iterrows():
    if idx == 2:
        continue
    updata_name = "检查结果"
    if row[updata_name]!="":
        have_value = row[updata_name]
    else:
        sheet_data.loc[idx,updata_name] = have_value

In [28]:
sheet_data["检查结果"] = sheet_data["检查结果"] + "," +sheet_data["Unnamed: 4"]

In [33]:
sheet_data["疾病"] = sheet_data["疾病"] + "/" + sheet_data["Unnamed: 1"]

In [35]:
sheet_data.drop(["Unnamed: 1"],axis=1,inplace=True)

In [39]:
for idx,row in sheet_data.iterrows():
    if row["防癌"]=="":
        sheet_data.loc[idx,"防癌"] = row["重疾"]
    if row["意外险"]=="":
        sheet_data.loc[idx,"意外险"] = row["重疾"]
    if row["护理险"]=="":
        sheet_data.loc[idx,"护理险"] = row["重疾"]
    if row["医疗险"]=="":
        sheet_data.loc[idx,"医疗险"] = row["重疾"]

In [40]:
sheet_data.head(20)

,疾病,资料,检查结果,重疾,防癌,意外险,护理险,医疗险
0,子宫/内膜肿瘤,病历、妇科超声、病理结果,"现症,",延期至术后或痊愈后,延期至术后或痊愈后,延期至术后或痊愈后,延期至术后或痊愈后,延期至术后或痊愈后
1,子宫/内膜肿瘤,病历、妇科超声、病理结果,"术后（诊刮后1个月、内镜切除后3个月、子宫切除后3年），病理良性且复查正常,",标体,标体,标体,标体,除外
2,子宫/子宫肉瘤,病历、妇科超声、病理结果,",",拒保,拒保,拒保,拒保,拒保
3,子宫/滋养细胞肿瘤\n（葡萄胎）,病历、妇科超声、HCG,"化疗结束3年后，连续复诊未见异常,",拒保,拒保,标体,标体,拒保
4,附件/多囊卵巢综合征,妇科超声、血脂、OGTT or 血糖+糖化、BMI、BP、ECG,"不存在心血管疾病风险因素,",标体,标体,标体,标体,除外
5,附件/多囊卵巢综合征,妇科超声、血脂、OGTT or 血糖+糖化、BMI、BP、ECG,"存在心血管疾病风险因素,",依据风险因素审核,依据风险因素审核,依据风险因素审核,依据风险因素审核,拒保
6,附件/卵巢肿瘤,病历、妇科超声、病理结果、肿瘤标记物,"现症,肿瘤标记物正常或未查，明确诊断为生理性囊肿、黄体囊肿或卵泡，最大直径＜40mm",标体,标体,标体,标体,除外
7,附件/卵巢肿瘤,病历、妇科超声、病理结果、肿瘤标记物,"现症,肿瘤标记物正常或未查，最大直径≥过40mm或描述较差*1",延期至术后或痊愈后,延期至术后或痊愈后,标体,标体,拒保
8,附件/卵巢肿瘤,病历、妇科超声、病理结果、肿瘤标记物,"现症,肿瘤标记物异常",拒保,拒保,拒保,拒保,拒保
9,附件/卵巢肿瘤,病历、妇科超声、病理结果、肿瘤标记物,"现症,畸胎瘤、囊腺瘤",延期至术后6个月,延期至术后6个月,延期至术后6个月,延期至术后6个月,延期至术后6个月
10,附件/卵巢肿瘤,病历、妇科超声、病理结果、肿瘤标记物,"未做治疗，自行吸收痊愈,",标体,标体,标体,标体,标体
11,附件/卵巢肿瘤,病历、妇科超声、病理结果、肿瘤标记物,"手术切除,病理良性，无复发",标体,标体,标体,标体,除外
12,附件/卵巢肿瘤,病历、妇科超声、病理结果、肿瘤标记物,"手术切除,病理良性，有复发",依据再发的具体情况审核,依据再发的具体情况审核,依据再发的具体情况审核,依据再发的具体情况审核,依据再发的具体情况审核
13,附件/卵巢肿瘤,病历、妇科超声、病理结果、肿瘤标记物,"手术切除,病理非良性",拒保,拒保,拒保,拒保,拒保
14,附件/输卵管肿瘤,病历、妇科超声、病理结果、肿瘤标记物,"现症,肿瘤标记物正常或未查，明确诊断为生理性囊肿、黄体囊肿或卵泡，最大直径＜40mm",标体,标体,标体,标体,除外
15,附件/输卵管肿瘤,病历、妇科超声、病理结果、肿瘤标记物,"现症,肿瘤标记物正常或未查，最大直径≥过40mm或描述较差*1",延期至术后或痊愈后,延期至术后或痊愈后,标体,标体,拒保
16,附件/输卵管肿瘤,病历、妇科超声、病理结果、肿瘤标记物,"现症,肿瘤标记物异常",拒保,拒保,拒保,拒保,拒保
17,附件/输卵管肿瘤,病历、妇科超声、病理结果、肿瘤标记物,"现症,畸胎瘤、囊腺瘤",延期至术后6个月,延期至术后6个月,延期至术后6个月,延期至术后6个月,延期至术后6个月
18,附件/输卵管肿瘤,病历、妇科超声、病理结果、肿瘤标记物,"未做治疗，自行吸收痊愈,",标体,标体,标体,标体,标体
19,附件/输卵管肿瘤,病历、妇科超声、病理结果、肿瘤标记物,"手术切除,病理良性，无复发",标体,标体,标体,标体,除外

In [42]:
with open("./save_data/妇科肿物.txt","w") as f:
    for idx,row in sheet_data.iterrows():
        item_ = row.to_json(force_ascii=False)
        f.write(item_ + '\n\n')

In [43]:
df_conclusions = pd.read_csv("./utils/disease_2_conclusion_v3.csv",keep_default_na=False)

In [46]:
df_conclusions_v2 = df_conclusions[df_conclusions["file_name"]!="妇科肿物.txt"]

In [47]:
df_conclusions_v2.head()

  disease_name file_name                                         conclusion
0     肺大疱（肺囊肿）    呼吸.txt  {'疾病名称': '肺大疱（肺囊肿）', '诊断': '未接受手术，连续 X 射线检查显示病...
1     肺大疱（肺囊肿）    呼吸.txt  {'疾病名称': '肺大疱（肺囊肿）', '诊断': '未接受手术，连续 X 射线检查显示病...
2     肺大疱（肺囊肿）    呼吸.txt  {'疾病名称': '肺大疱（肺囊肿）', '诊断': '未接受手术，连续 X 射线检查显示病...
3     肺大疱（肺囊肿）    呼吸.txt  {'疾病名称': '肺大疱（肺囊肿）', '诊断': '未接受手术，连续 X 射线检查显示病...
4     肺大疱（肺囊肿）    呼吸.txt  {'疾病名称': '肺大疱（肺囊肿）', '诊断': '未接受手术，连续 X 射线检查显示病...

In [48]:
data_save = []
for idx,row in sheet_data.iterrows():
    item_ = row.to_json(force_ascii=False)
    dict_data = {
        "disease_name":row["疾病"],
        "file_name":"妇科肿物.txt",
        "conclusion":item_
    }
    data_save.append(dict_data)

In [50]:
df_conclusions_save = pd.concat([df_conclusions_v2,pd.DataFrame(data_save)],ignore_index=True)

In [51]:
df_conclusions_save[df_conclusions_save["file_name"]=="妇科肿物.txt"].head()

,disease_name,file_name,conclusion
1031,子宫/内膜肿瘤,妇科肿物.txt,"{""疾病"":""子宫\/内膜肿瘤"",""资料"":""病历、妇科超声、病理结果"",""检查结果"":""现..."
1032,子宫/内膜肿瘤,妇科肿物.txt,"{""疾病"":""子宫\/内膜肿瘤"",""资料"":""病历、妇科超声、病理结果"",""检查结果"":""术..."
1033,子宫/子宫肉瘤,妇科肿物.txt,"{""疾病"":""子宫\/子宫肉瘤"",""资料"":""病历、妇科超声、病理结果"",""检查结果"":"",..."
1034,子宫/滋养细胞肿瘤\n（葡萄胎）,妇科肿物.txt,"{""疾病"":""子宫\/滋养细胞肿瘤\n（葡萄胎）"",""资料"":""病历、妇科超声、HCG"",""..."
1035,附件/多囊卵巢综合征,妇科肿物.txt,"{""疾病"":""附件\/多囊卵巢综合征"",""资料"":""妇科超声、血脂、OGTT or 血糖+糖..."

In [52]:
df_conclusions_save.to_csv("./utils/disease_2_conclusion_v4.csv",index=False)