In [1]:
import requests
import pandas as pd
import json
import openai
from openai import OpenAI
import time
import re
import os

In [2]:
#大模型
client = OpenAI(
    api_key="token-vulcan",  # 输入你的 API Key
    base_url="http://219.147.99.170:50020/v1"
)


def qa_base(messages):
    completion = client.chat.completions.create(
        model="Qwen2-5-7B",
        messages=messages,
        logprobs=False,
        # stream=True  # 开启流式输出
    )
    return completion.choices[0].message.content
    # if compile.status_code == 200:
    #     result = completion[0].choices[0].delta.content
    #     return result
    # else:
    #     print(f"请求失败，状态码: {completion.status_code}")
    #     return ""

In [3]:
df_dise_2_conc = pd.read_csv("./disease_2_conclusion.csv",keep_default_na=False)
df_dise_2_keyword = pd.read_excel("./中再疾病函数对照表.xlsx",keep_default_na=False)

In [42]:
df_dise_2_conc[df_dise_2_conc["file_name"]=="肺结节.txt"].head()

    disease_name file_name                                         conclusion
867          肺结节   肺结节.txt  {'诊断': '诊断', '病情现状': '结节大小', '': '发现时间（距离第一次影像...
868          肺结节   肺结节.txt  {'诊断': '已接受手术，有明确诊断', '病情现状': '——', '': '——', ...
869          肺结节   肺结节.txt  {'诊断': '已接受活检，有明确诊断', '病情现状': '——', '': '——', ...
870          肺结节   肺结节.txt  {'诊断': '无明确诊断，只见于当前影像，无既往影像可比较', '病情现状': '——',...
871          肺结节   肺结节.txt  {'诊断': '无明确诊断，只见于当前影像，无既往影像可比较', '病情现状': '——',...

In [4]:
for idx,row in df_dise_2_conc.iterrows():
    if row["file_name"]=="肺结节.txt":
        df_dise_2_conc.loc[idx,"disease_name"] = "肺结节"

In [8]:
df_dise_2_conc_v2 = df_dise_2_conc.drop(104,axis=0,inplace=False)
df_dise_2_conc_v2[df_dise_2_conc_v2["disease_name"]=="视网膜病的病因未明，正在进行检查"].head()

Empty DataFrame
Columns: [disease_name, file_name, conclusion]
Index: []

In [9]:
df_dise_2_conc_v2.to_csv("./utils/disease_2_conclusion_v2.csv",index=False)

In [7]:
df_dise_2_conc[df_dise_2_conc["disease_name"]=="视网膜病的病因未明，正在进行检查"].head()

,disease_name,file_name,conclusion
104,视网膜病的病因未明，正在进行检查,五官科.txt,"{'疾病名称': '视网膜病的病因未明，正在进行检查', '诊断': '视网膜病的病因未明，..."

In [5]:
disease_name = set([word for word in df_dise_2_conc["disease_name"].tolist() if word!="视网膜病的病因未明，正在进行检查"])
print(len(disease_name))
print(disease_name)

227
{'继发于慢性病的贫血', '戊型肝炎', '脊柱裂', '癫痫', '结核病', '胰腺炎', '新生儿缺氧缺血性脑病', '视网膜中央动脉血栓症', '心内膜炎', '新生儿溶血病', '心肌炎', '急性肾病综合征（急性肾小球肾炎、感染后肾小球肾炎）', '纵膈肿瘤', '呼吸衰竭', '雅库氏关节病', '植物神经功能紊乱', '耳鸣', '腮腺癌', '肺水肿', '四肢骨折', '胃息肉', '肺结节', '前列腺炎', '鼻炎', '腰椎间盘突出', '乳腺增生', '血红蛋白尿', 'EB病毒感染', '便潜血', '带状疱疹', '脾脏创伤', '多发性硬化', '风湿热', '肾积水', '支气管扩张', '慢性间质性肾炎（慢性肾小管间质性肾炎）', '雷诺综合征', '头痛', '白内障', '股骨头坏死', '气管炎/支气管炎', '肾病综合征（慢性）', '流行性出血热', '胃炎', '视网膜血管病变', '皮肌炎', '肾下垂', '先天性肾畸形/单肾', '附件', '痔疮', '缺铁性贫血', '肛瘘', '子宫出血', '梅毒', '胸膜炎', '扁桃体炎', '烧伤', '乳腺炎、脓肿', '肺动静脉瘘', '重症肌无力', '巨幼细胞性贫血', '色素性视网膜炎', '视网膜血管变性', '腺样体肥大', '丙型肝炎', '扩张性心肌病', '肺纤维化', '子宫内膜增厚（内膜厚度超过10mm）', '甲状腺炎', '主动脉瓣疾病', '焦虑症', '视网膜中央静脉血栓形成', '甲状腺手术', '颈椎病', '脑损伤', '子宫脱垂', '腰肌劳损', '特发性血小板减少紫癜', '腰椎滑脱', '宫颈上皮内瘤变\n', '甲亢', '病理分类： 乳头状癌、滤泡性癌（55岁以下）', '肝性脑病', '肠吸收不良', '慢性肾小球肾炎', '颅咽管瘤', '乳腺假体植入', '视网膜出血', '急性细菌性肾盂肾炎、急性肾盂肾炎', '面神经炎\n（面瘫）', 'HPV感染', '肝血管瘤', '糖尿病前期', '手术', '宫颈癌', '肺炎\n（不包括新冠肺炎）', '血吸虫病', '泌尿系感染', '甲状腺结节', '（下肢）静脉曲张', '类风湿性关节炎', '乳腺结节、囊肿、占位、异常回声', '精神分裂症', '脾大', '视神经炎', '多囊肾/家族史', '结直肠癌', '耳聋', '霉菌性阴道炎', '肛裂', '泌尿系结石（无高血压和肾功能损害）', '阴道壁膨出', '肛周脓肿', '流行性乙型脑炎', '病理分类： 乳头状癌、滤泡性癌（55岁以上）', '疑似错构瘤的肺结节', '子宫', '慢性肾盂肾炎', '椎管狭窄已手术', '胸膜间皮瘤', '系统性红斑狼疮', '儿童乳腺', ' 地中海贫血', '颈椎椎管狭窄', '肾错构瘤', '神经衰弱', '自发性气胸', '抑郁症', '青光眼', '腰椎椎管狭窄', '哮喘', '2型糖尿病', '腮腺良性肿瘤', '新生儿高胆红素血症', '甲型肝炎', '甲减', '子宫内膜异位症', '淋菌性阴道炎', '慢性结/直肠炎/溃疡性结肠炎', '血压升高', '乙型肝炎', '臂丛神经痛', '缺血性脑血管病', '腺瘤、息肉', '纵膈气肿', '颅内神经纤维瘤', '胆囊炎', '各类肾炎，包含其他因素', '视网膜脱离', '酒精性肝病', '失眠症', '肝囊肿', '心包炎/心包积液', '心律失常', '室间隔缺损', '过敏性紫癜', '食管', '结节病', '强直性脊柱炎', '其他心脏结构异常', '子宫内膜息肉', '更年期综合征', '阻塞性睡眠呼吸暂停综合征', '咽喉炎', '风湿性关节炎', '干燥综合征', '1型糖尿病', '肺错构瘤', '美尼尔氏病', '肌营养不良症', '异位妊娠', '脾功能亢进', '肺大疱（肺囊肿）', '胆囊息肉', '子宫肌瘤', '心肌病家族史', '滴虫性阴道炎', '流行性腮腺炎', '鼻息肉', '肺动脉瓣疾病', '二尖瓣/三尖瓣', '脂肪肝*', '退行性改变', '脑膜炎/脑脊髓膜炎', '胆管炎', '声带息肉', '新生儿卵圆孔未闭', '近视眼手术', '肝硬化', '肥厚性心肌病、限制性心肌病、非致密化心肌病、致心律失常性心肌病等', '鼻中隔偏曲', '脑梗塞', '盆腔积液', '急性失血性贫血', '肺脓肿', '三叉神经痛', '中性粒细胞减少症', '胆结石', '新生儿房/室间隔缺损', '房间隔缺损', '肠梗阻', '心脏肥大/增大/扩大', '宫颈纳囊', '新生儿呼吸窘迫综合征', '短暂性脑缺血发作', '男性乳腺', '骨髓增生异常综合征', 'HP阳性、幽门螺杆菌感染', '病理分类：间变性癌、未分化癌、髓样癌等', '腹膜炎', '肾动脉狭窄', '肝内胆管结石', '中耳炎', '消化性溃疡', '肺气肿', '巨结肠', '肌营养不良症家族史', '肾囊肿（排除了肾功能损害的）', '宫颈炎', '急性间质性肾炎（急性感染性肾小管间质性肾炎）', '克罗恩病', '新生儿心肌损害', '肺栓塞', '胆脂瘤', '•急性轴索型神经病\n•急性特发性炎症性多发性神经病\n•急性炎症性脱髓鞘性多发性神经病 (AIDP)\n•急性炎症性多发性神经病 (AIPN)\n•急性运动性轴索型神经病 (AMAN)\n•急性运动感觉性轴索型神经病 (AMSAN)\n•慢性炎症性脱髓鞘性神经病 (CIDP)\n•慢性炎症性多发性神经病 (CIP)\n•慢性复发性炎症性多发性神经病 (CIRP)\n•多发性神经根性神经炎\n•吉兰-巴雷综合征\n•格林-巴利综合征\n•GB综合征（Guillain-Barré）', '鼻部假体植入', '遗传性出血性毛细血管扩张症'}

In [80]:
df_dise_2_keyword_kl = df_dise_2_keyword[df_dise_2_keyword["KL_match_disease"].apply(lambda x:x!="")]
print(df_dise_2_keyword_kl.shape)
df_dise_2_keyword_kl[df_dise_2_keyword_kl["disease_n"]=="子宫内膜息肉"].head()
# df_dise_2_keyword_kl.head()

(230, 14)

,def_name,HBZS_def,HBZS_did,disease_n,disease_list,kwords,CI,MI,ADB,Life,ZZ_match_disease,RZ_match_disease,MZ_match_disease,KL_match_disease
492,ZiGNM_XR,ZiGXR,104,子宫内膜息肉,['子宫内膜息肉'],"[['子宫', '宫腔'], ['内膜息肉', '息肉', '高回声']]",子宫内膜恶性肿瘤（包括原位癌）及其复发和转移,子宫内膜息肉,,,zigongzhongliu,zigongneimozhongliu,7881,493

In [70]:

disease_n = set([word for word in df_dise_2_keyword_kl["disease_n"].tolist() if word != ""])
print(len(disease_n))
print(disease_n)

230
{'气胸', '糖耐量异常', '急性肾小球肾炎', '宫颈肿瘤', '二尖瓣反流', '病态窦房结综合征', '儿童乳腺发育', '肾病综合征', '肝血管瘤', '风湿性关节炎', '滋养细胞肿瘤', '焦虑障碍', '肠梗阻', '前列腺炎', '幽门螺旋杆菌感染', '视网膜变性', '主动脉瓣狭窄', '系统性红斑狼疮', '紫癜性肾炎', '颅咽管瘤', '肾下垂', '重症肌无力', '卵巢切除手术', '子宫内膜癌', '结节病', '心包积液', '巨结肠', '乳腺结节', '心肌梗塞', '视网膜出血', '膀胱炎', '宫颈炎', '三叉神经痛', '肾动脉狭窄', '肾炎', '乳腺炎', '血吸虫病', '肝性脑病', '烧伤', '溶血病', '肌营养不良症', '肝囊肿', '动脉栓塞', '支气管扩张症', '主动脉瓣关闭不全', '青光眼', '戊型肝炎', '肛瘘', '子宫肌瘤', '格林巴利综合征', '子宫肉瘤', '肺动静脉瘘', '心肌桥', '腮腺癌', '乙型肝炎', '子宫切除手术', '梗阻性睡眠呼吸暂停', '慢性支气管炎', '脊柱裂', '胆囊切除', '心率不齐', '退行性改变', '宫颈上皮内瘤变', '鼻炎', '肺纤维化', '脑出血', '肺动脉瓣关闭不全', '白内障', '空腹血糖受损', '慢性丙型肝炎', '骨髓增生异常综合征', '房性期前收缩', '梅毒', '肺炎', '缺血缺氧性脑病', '肺水肿', '视网膜色素变性', '气管炎', '肺囊肿', '神经系统肿瘤', '尿道炎', '子宫内膜增生', '流行性乙型脑炎', '脑膜炎', '更年期综合征', '肺或支气管良性肿瘤', '肺结节病', '慢性胰腺炎', '抑郁症', '头痛', '胸膜间皮瘤', 'II型糖尿病', '心肌损害', '心绞痛', '甲状腺结节', '缺铁性贫血', '腰椎滑脱', '子宫内膜异位症', '臂丛神经痛', '雷诺综合征', '脑卒中', '颅脑损伤', '声带结节', '先天性肾畸形', '干眼症', '脂肪肝', '糖尿病性视网膜病变', '卵巢癌', '血红蛋白尿', '酒精性脂肪肝', '肺气肿', '高血压性视网膜病变', '中耳炎', '呼吸衰竭', '输尿管结石', '美尼尔氏症', '室性期前收缩', '腰肌劳损', '便潜血', '植物神经功能紊乱', '腹膜炎', '风湿热', '房室传导阻滞', '视网膜损伤', '鼻中隔偏曲', '陶氏腔积液', '急性丙型肝炎', '肛裂', 'HPV感染', '强直性脊柱炎', '二尖瓣狭窄', '听力异常', '雅库氏关节病', '流行性出血热', '膀胱结石', '肠息肉', '胆脂瘤', '肺结核', '地中海贫血', '肾结石', '多发性硬化', '癫痫', '心内膜炎', '鼻部假体植入', '精神分裂症', '宫颈原位癌', '子宫内膜息肉', '心肌炎', '脾大', '痔疮', '鼻腺体肥大', '乳腺假体植入', '良性胸腺瘤', '脾功能亢进', '甲型肝炎', '肾良性肿瘤', '遗传性出血性毛细血管扩张症', '心包炎', '颅内神经纤维瘤', '消化性溃疡', '肺外结核', '阴道壁膨出', '室颤', '疱疹', '耳鸣', '游走心率', '溃疡性结肠炎', '房间隔缺损', '卵圆孔未闭', '卵巢囊肿', '近视眼手术', '异位妊娠', '睡眠障碍', 'EB病毒感染', '肾盂肾炎', '甲状腺功能减退', '视网膜中央静脉血栓形成', '胆囊疾病', '短暂性脑缺血发作', '股骨头坏死', '动脉硬化性视网膜病变', '甲状腺功能亢进', '肺大疱', '缺血性脑血管病', '房颤', '多囊肾', '哮喘', '腮腺炎', '恶性胸腺瘤', '肾囊肿', '肾盂积水', '假性乳房发育', '家族性高胆红素血症', '胸膜炎', '鼻息肉', '胆囊息肉', '新生儿呼吸窘迫综合征', '神经衰弱', '宫颈囊肿', '急性胰腺炎', '阵发性心动过速', '肝硬化', '乳腺增生', '胆管结石', '新生儿室间隔缺损', '周围性面瘫', '静脉曲张', '甲状腺炎', '紫癜', '胆道感染', '子宫脱垂', '心脏溶栓或搭桥', '先天性白内障', '阴道炎', '脾破裂', '干燥综合征', '室性心动过速', '结直肠癌', '高血压', '多肌炎', '冠心病', '视神经炎', '扁桃体炎', '室间隔缺损', '节段性肠炎', '预激综合征', '中性粒细胞减少症', '类风湿性关节炎', 'I型糖尿病', '腮腺良性肿瘤'}

In [ ]:
if "zi"

In [46]:
#bad key:视网膜病的病因未明，正在进行检查,诊断，
df_dise_2_conc[df_dise_2_conc["disease_name"]=="肺结节"].head()

    disease_name file_name                                         conclusion
867          肺结节   肺结节.txt  {'诊断': '诊断', '病情现状': '结节大小', '': '发现时间（距离第一次影像...
868          肺结节   肺结节.txt  {'诊断': '已接受手术，有明确诊断', '病情现状': '——', '': '——', ...
869          肺结节   肺结节.txt  {'诊断': '已接受活检，有明确诊断', '病情现状': '——', '': '——', ...
870          肺结节   肺结节.txt  {'诊断': '无明确诊断，只见于当前影像，无既往影像可比较', '病情现状': '——',...
871          肺结节   肺结节.txt  {'诊断': '无明确诊断，只见于当前影像，无既往影像可比较', '病情现状': '——',...

In [72]:
all_have = disease_name & disease_n
print(len(all_have))
print(all_have)
disease_name_only = disease_name - all_have
print(len(disease_name_only))
print(disease_name_only)
disease_n_only = disease_n - all_have
print(len(disease_n_only))
print(disease_n_only)

104
{'肝血管瘤', '风湿性关节炎', '前列腺炎', '肠梗阻', '系统性红斑狼疮', '颅咽管瘤', '肾下垂', '重症肌无力', '结节病', '巨结肠', '视网膜出血', '宫颈炎', '三叉神经痛', '肾动脉狭窄', '血吸虫病', '肝性脑病', '烧伤', '肌营养不良症', '肝囊肿', '戊型肝炎', '青光眼', '肛瘘', '子宫肌瘤', '肺动静脉瘘', '腮腺癌', '乙型肝炎', '脊柱裂', '退行性改变', '鼻炎', '肺纤维化', '白内障', '骨髓增生异常综合征', '梅毒', '肺水肿', '流行性乙型脑炎', '更年期综合征', '抑郁症', '头痛', '胸膜间皮瘤', '腰椎滑脱', '甲状腺结节', '缺铁性贫血', '子宫内膜异位症', '臂丛神经痛', '雷诺综合征', '血红蛋白尿', '肺气肿', '呼吸衰竭', '中耳炎', '植物神经功能紊乱', '腰肌劳损', '便潜血', '腹膜炎', '风湿热', '肛裂', '鼻中隔偏曲', 'HPV感染', '强直性脊柱炎', '雅库氏关节病', '流行性出血热', '胆脂瘤', '多发性硬化', '癫痫', '心内膜炎', '鼻部假体植入', '精神分裂症', '子宫内膜息肉', '心肌炎', '脾大', '乳腺假体植入', '痔疮', '脾功能亢进', '甲型肝炎', '遗传性出血性毛细血管扩张症', '颅内神经纤维瘤', '消化性溃疡', '阴道壁膨出', '耳鸣', '房间隔缺损', '近视眼手术', '异位妊娠', 'EB病毒感染', '视网膜中央静脉血栓形成', '短暂性脑缺血发作', '股骨头坏死', '缺血性脑血管病', '哮喘', '胸膜炎', '鼻息肉', '新生儿呼吸窘迫综合征', '胆囊息肉', '神经衰弱', '肝硬化', '乳腺增生', '甲状腺炎', '子宫脱垂', '结直肠癌', '干燥综合征', '视神经炎', '扁桃体炎', '室间隔缺损', '中性粒细胞减少症', '类风湿性关节炎', '腮腺良性肿瘤'}
123
{'新生儿房/室间隔缺损', '甲亢', '泌尿系结石（无高血压和肾功能损害）', '1型糖尿病', '各类肾炎，包含其他因素', '新生儿卵圆孔未闭', '颈椎椎管狭窄', '盆腔积液', '心脏肥大/增大/扩大', '流行性腮腺炎', '胆管炎', '慢性结/直肠炎/溃疡性结肠炎', '肺脓肿', '甲状腺手术', '多囊肾/家族史', '腰椎椎管狭窄', '视网膜中央动脉血栓症', '儿童乳腺', '肺大疱（肺囊肿）', '•急性轴索型神经病\n•急性特发性炎症性多发性神经病\n•急性炎症性脱髓鞘性多发性神经病 (AIDP)\n•急性炎症性多发性神经病 (AIPN)\n•急性运动性轴索型神经病 (AMAN)\n•急性运动感觉性轴索型神经病 (AMSAN)\n•慢性炎症性脱髓鞘性神经病 (CIDP)\n•慢性炎症性多发性神经病 (CIP)\n•慢性复发性炎症性多发性神经病 (CIRP)\n•多发性神经根性神经炎\n•吉兰-巴雷综合征\n•格林-巴利综合征\n•GB综合征（Guillain-Barré）', '过敏性紫癜', '宫颈癌', '食管', '霉菌性阴道炎', '慢性肾小球肾炎', '气管炎/支气管炎', '腰椎间盘突出', '颈椎病', '腺瘤、息肉', '克罗恩病', '脑梗塞', '丙型肝炎', '脾脏创伤', '脑损伤', '急性细菌性肾盂肾炎、急性肾盂肾炎', '胃炎', '结核病', '淋菌性阴道炎', '美尼尔氏病', '病理分类： 乳头状癌、滤泡性癌（55岁以上）', '肺炎\n（不包括新冠肺炎）', '血压升高', '椎管狭窄已手术', '心包炎/心包积液', '急性肾病综合征（急性肾小球肾炎、感染后肾小球肾炎）', '慢性间质性肾炎（慢性肾小管间质性肾炎）', '肾病综合征（慢性）', '肾囊肿（排除了肾功能损害的）', '肺动脉瓣疾病', '腺样体肥大', '四肢骨折', '心律失常', '手术', '巨幼细胞性贫血', '特发性血小板减少紫癜', '带状疱疹', '急性间质性肾炎（急性感染性肾小管间质性肾炎）', '纵膈气肿', '自发性气胸', '新生儿高胆红素血症', '肥厚性心肌病、限制性心肌病、非致密化心肌病、致心律失常性心肌病等', 'HP阳性、幽门螺杆菌感染', '附件', '新生儿溶血病', '肌营养不良症家族史', '肛周脓肿', '阻塞性睡眠呼吸暂停综合征', '肠吸收不良', '支气管扩张', '胆结石', '纵膈肿瘤', '新生儿缺氧缺血性脑病', '色素性视网膜炎', '甲减', '乳腺炎、脓肿', '视网膜脱离', '咽喉炎', '失眠症', '胰腺炎', '肾错构瘤', '胆囊炎', '子宫', '乳腺结节、囊肿、占位、异常回声', '肺栓塞', '脑膜炎/脑脊髓膜炎', '耳聋', '面神经炎\n（面瘫）', '滴虫性阴道炎', ' 地中海贫血', '宫颈上皮内瘤变\n', '先天性肾畸形/单肾', '（下肢）静脉曲张', '继发于慢性病的贫血', '疑似错构瘤的肺结节', '视网膜血管病变', '心肌病家族史', '糖尿病前期', '肝内胆管结石', '脂肪肝*', '皮肌炎', '泌尿系感染', '2型糖尿病', '肺错构瘤', '酒精性肝病', '主动脉瓣疾病', '病理分类： 乳头状癌、滤泡性癌（55岁以下）', '肾积水', '肺结节', '扩张性心肌病', '其他心脏结构异常', '子宫出血', '宫颈纳囊', '声带息肉', '急性失血性贫血', '二尖瓣/三尖瓣', '慢性肾盂肾炎', '男性乳腺', '病理分类：间变性癌、未分化癌、髓样癌等', '新生儿心肌损害', '子宫内膜增厚（内膜厚度超过10mm）', '胃息肉', '视网膜血管变性', '焦虑症'}
126
{'气胸', '糖耐量异常', '急性肾小球肾炎', '二尖瓣反流', '病态窦房结综合征', '儿童乳腺发育', '肾病综合征', '滋养细胞肿瘤', '焦虑障碍', '幽门螺旋杆菌感染', '视网膜变性', '主动脉瓣狭窄', '紫癜性肾炎', '卵巢切除手术', '子宫内膜癌', '心包积液', '乳腺结节', '心肌梗塞', '膀胱炎', '肾炎', '乳腺炎', 'I型糖尿病', '溶血病', '动脉栓塞', '支气管扩张症', '主动脉瓣关闭不全', '心肌桥', '格林巴利综合征', '子宫肉瘤', '子宫切除手术', '梗阻性睡眠呼吸暂停', '慢性支气管炎', '胆囊切除', '心率不齐', '宫颈上皮内瘤变', '脑出血', '肺动脉瓣关闭不全', '空腹血糖受损', '慢性丙型肝炎', '房性期前收缩', '肺炎', '缺血缺氧性脑病', '视网膜色素变性', '气管炎', '肺囊肿', '神经系统肿瘤', '尿道炎', '子宫内膜增生', '脑膜炎', '肺或支气管良性肿瘤', '肺结节病', '慢性胰腺炎', 'II型糖尿病', '心肌损害', '心绞痛', '脑卒中', '颅脑损伤', '声带结节', '先天性肾畸形', '干眼症', '脂肪肝', '糖尿病性视网膜病变', '卵巢癌', '酒精性脂肪肝', '高血压性视网膜病变', '输尿管结石', '美尼尔氏症', '室性期前收缩', '房室传导阻滞', '视网膜损伤', '陶氏腔积液', '急性丙型肝炎', '二尖瓣狭窄', '听力异常', '膀胱结石', '肠息肉', '肺结核', '地中海贫血', '肾结石', '宫颈原位癌', '鼻腺体肥大', '良性胸腺瘤', '肾良性肿瘤', '心包炎', '肺外结核', '室颤', '疱疹', '游走心率', '溃疡性结肠炎', '卵圆孔未闭', '卵巢囊肿', '睡眠障碍', '肾盂肾炎', '甲状腺功能减退', '胆囊疾病', '动脉硬化性视网膜病变', '甲状腺功能亢进', '肺大疱', '房颤', '多囊肾', '腮腺炎', '恶性胸腺瘤', '肾囊肿', '肾盂积水', '假性乳房发育', '家族性高胆红素血症', '宫颈囊肿', '急性胰腺炎', '阵发性心动过速', '胆管结石', '新生儿室间隔缺损', '周围性面瘫', '静脉曲张', '紫癜', '胆道感染', '心脏溶栓或搭桥', '先天性白内障', '阴道炎', '脾破裂', '室性心动过速', '高血压', '多肌炎', '冠心病', '节段性肠炎', '预激综合征', '宫颈肿瘤'}

# 编辑距离计算疾病相似度

In [29]:
def edit_distance(str1, str2):
    """计算两个字符串的编辑距离

    Args:
        str1: 字符串1
        str2: 字符串2

    Returns:
        int: 编辑距离
    """

    m = len(str1)
    n = len(str2)

    # 初始化二维数组dp，dp[i][j]表示str1[:i]和str2[:j]的编辑距离
    dp = [[i+j for j in range(n+1)] for i in range(m+1)]
    for i in range(1, m+1):
        dp[i][0] = i
    for j in range(1, n+1):
        dp[0][j] = j

    for i in range(1, m+1):
        for j in range(1, n+1):
            if str1[i-1] == str2[j-1]:
                cost = 0
            else:
                cost = 1
            dp[i][j] = min(dp[i-1][j]+1, dp[i][j-1]+1, dp[i-1][j-1]+cost)

    return dp[m][n]

def normalized_similarity(str1, str2):
    distance = edit_distance(str1, str2)
    max_len = max(len(str1), len(str2))
    similarity = 1 - distance / max_len
    return similarity

# 示例用法
str1 = "kitten"
# str2 = "sitting"
str2 = "kitte"

distance = edit_distance(str2, str1)
print("编辑距离:", distance)

distance_nor = normalized_similarity(str1,str2)
print(round(distance_nor,4))

编辑距离: 1
0.8333

# 构建 中再疾病函数对照表的disease_n 到 disease_2_concluson中的disease_name的匹配

In [75]:
all_have = disease_name & disease_n
print(len(all_have))
print(all_have)
disease_name_only = disease_name - all_have
print(len(disease_name_only))
print("disease name only",disease_name_only)
disease_n_only = disease_n - all_have
print(len(disease_n_only))
print("disease n only",disease_n_only)
map_key_2_dise = {}
for key in list(disease_n_only)+["肾结晶"]:
    if key in ["视网膜病的病因未明，正在进行检查","诊断",""]:
        continue
    simil_score = {}
    for key_n in disease_name_only:
        score = normalized_similarity(key,key_n)
        if score == 0.0:
            continue
        simil_score[key_n] = score
    sorted_dict = sorted(simil_score.items(), key=lambda x: x[1], reverse=True)
    result =sorted_dict[:5]
    map_key_2_dise[key] = result
print(map_key_2_dise)

104
{'肝血管瘤', '风湿性关节炎', '前列腺炎', '肠梗阻', '系统性红斑狼疮', '颅咽管瘤', '肾下垂', '重症肌无力', '结节病', '巨结肠', '视网膜出血', '宫颈炎', '三叉神经痛', '肾动脉狭窄', '血吸虫病', '肝性脑病', '烧伤', '肌营养不良症', '肝囊肿', '戊型肝炎', '青光眼', '肛瘘', '子宫肌瘤', '肺动静脉瘘', '腮腺癌', '乙型肝炎', '脊柱裂', '退行性改变', '鼻炎', '肺纤维化', '白内障', '骨髓增生异常综合征', '梅毒', '肺水肿', '流行性乙型脑炎', '更年期综合征', '抑郁症', '头痛', '胸膜间皮瘤', '腰椎滑脱', '甲状腺结节', '缺铁性贫血', '子宫内膜异位症', '臂丛神经痛', '雷诺综合征', '血红蛋白尿', '肺气肿', '呼吸衰竭', '中耳炎', '植物神经功能紊乱', '腰肌劳损', '便潜血', '腹膜炎', '风湿热', '肛裂', '鼻中隔偏曲', 'HPV感染', '强直性脊柱炎', '雅库氏关节病', '流行性出血热', '胆脂瘤', '多发性硬化', '癫痫', '心内膜炎', '鼻部假体植入', '精神分裂症', '子宫内膜息肉', '心肌炎', '脾大', '乳腺假体植入', '痔疮', '脾功能亢进', '甲型肝炎', '遗传性出血性毛细血管扩张症', '颅内神经纤维瘤', '消化性溃疡', '阴道壁膨出', '耳鸣', '房间隔缺损', '近视眼手术', '异位妊娠', 'EB病毒感染', '视网膜中央静脉血栓形成', '短暂性脑缺血发作', '股骨头坏死', '缺血性脑血管病', '哮喘', '胸膜炎', '鼻息肉', '新生儿呼吸窘迫综合征', '胆囊息肉', '神经衰弱', '肝硬化', '乳腺增生', '甲状腺炎', '子宫脱垂', '结直肠癌', '干燥综合征', '视神经炎', '扁桃体炎', '室间隔缺损', '中性粒细胞减少症', '类风湿性关节炎', '腮腺良性肿瘤'}
123
disease name only {'新生儿房/室间隔缺损', '甲亢', '泌尿系结石（无高血压和肾功能损害）', '1型糖尿病', '各类肾炎，包含其他因素', '新生儿卵圆孔未闭', '颈椎椎管狭窄', '盆腔积液', '心脏肥大/增大/扩大', '流行性腮腺炎', '胆管炎', '慢性结/直肠炎/溃疡性结肠炎', '肺脓肿', '甲状腺手术', '多囊肾/家族史', '腰椎椎管狭窄', '视网膜中央动脉血栓症', '儿童乳腺', '肺大疱（肺囊肿）', '•急性轴索型神经病\n•急性特发性炎症性多发性神经病\n•急性炎症性脱髓鞘性多发性神经病 (AIDP)\n•急性炎症性多发性神经病 (AIPN)\n•急性运动性轴索型神经病 (AMAN)\n•急性运动感觉性轴索型神经病 (AMSAN)\n•慢性炎症性脱髓鞘性神经病 (CIDP)\n•慢性炎症性多发性神经病 (CIP)\n•慢性复发性炎症性多发性神经病 (CIRP)\n•多发性神经根性神经炎\n•吉兰-巴雷综合征\n•格林-巴利综合征\n•GB综合征（Guillain-Barré）', '过敏性紫癜', '宫颈癌', '食管', '霉菌性阴道炎', '慢性肾小球肾炎', '气管炎/支气管炎', '腰椎间盘突出', '颈椎病', '腺瘤、息肉', '克罗恩病', '脑梗塞', '丙型肝炎', '脾脏创伤', '脑损伤', '急性细菌性肾盂肾炎、急性肾盂肾炎', '胃炎', '结核病', '淋菌性阴道炎', '美尼尔氏病', '病理分类： 乳头状癌、滤泡性癌（55岁以上）', '肺炎\n（不包括新冠肺炎）', '血压升高', '椎管狭窄已手术', '心包炎/心包积液', '急性肾病综合征（急性肾小球肾炎、感染后肾小球肾炎）', '慢性间质性肾炎（慢性肾小管间质性肾炎）', '肾病综合征（慢性）', '肾囊肿（排除了肾功能损害的）', '肺动脉瓣疾病', '腺样体肥大', '四肢骨折', '心律失常', '手术', '巨幼细胞性贫血', '特发性血小板减少紫癜', '带状疱疹', '急性间质性肾炎（急性感染性肾小管间质性肾炎）', '纵膈气肿', '自发性气胸', '新生儿高胆红素血症', '肥厚性心肌病、限制性心肌病、非致密化心肌病、致心律失常性心肌病等', 'HP阳性、幽门螺杆菌感染', '附件', '新生儿溶血病', '肌营养不良症家族史', '肛周脓肿', '阻塞性睡眠呼吸暂停综合征', '肠吸收不良', '支气管扩张', '胆结石', '纵膈肿瘤', '新生儿缺氧缺血性脑病', '色素性视网膜炎', '甲减', '乳腺炎、脓肿', '视网膜脱离', '咽喉炎', '失眠症', '胰腺炎', '肾错构瘤', '胆囊炎', '子宫', '乳腺结节、囊肿、占位、异常回声', '肺栓塞', '脑膜炎/脑脊髓膜炎', '耳聋', '面神经炎\n（面瘫）', '滴虫性阴道炎', ' 地中海贫血', '宫颈上皮内瘤变\n', '先天性肾畸形/单肾', '（下肢）静脉曲张', '继发于慢性病的贫血', '疑似错构瘤的肺结节', '视网膜血管病变', '心肌病家族史', '糖尿病前期', '肝内胆管结石', '脂肪肝*', '皮肌炎', '泌尿系感染', '2型糖尿病', '肺错构瘤', '酒精性肝病', '主动脉瓣疾病', '病理分类： 乳头状癌、滤泡性癌（55岁以下）', '肾积水', '肺结节', '扩张性心肌病', '其他心脏结构异常', '子宫出血', '宫颈纳囊', '声带息肉', '急性失血性贫血', '二尖瓣/三尖瓣', '慢性肾盂肾炎', '男性乳腺', '病理分类：间变性癌、未分化癌、髓样癌等', '新生儿心肌损害', '子宫内膜增厚（内膜厚度超过10mm）', '胃息肉', '视网膜血管变性', '焦虑症'}
126
disease n only {'气胸', '糖耐量异常', '急性肾小球肾炎', '二尖瓣反流', '病态窦房结综合征', '儿童乳腺发育', '肾病综合征', '滋养细胞肿瘤', '焦虑障碍', '幽门螺旋杆菌感染', '视网膜变性', '主动脉瓣狭窄', '紫癜性肾炎', '卵巢切除手术', '子宫内膜癌', '心包积液', '乳腺结节', '心肌梗塞', '膀胱炎', '肾炎', '乳腺炎', 'I型糖尿病', '溶血病', '动脉栓塞', '支气管扩张症', '主动脉瓣关闭不全', '心肌桥', '格林巴利综合征', '子宫肉瘤', '子宫切除手术', '梗阻性睡眠呼吸暂停', '慢性支气管炎', '胆囊切除', '心率不齐', '宫颈上皮内瘤变', '脑出血', '肺动脉瓣关闭不全', '空腹血糖受损', '慢性丙型肝炎', '房性期前收缩', '肺炎', '缺血缺氧性脑病', '视网膜色素变性', '气管炎', '肺囊肿', '神经系统肿瘤', '尿道炎', '子宫内膜增生', '脑膜炎', '肺或支气管良性肿瘤', '肺结节病', '慢性胰腺炎', 'II型糖尿病', '心肌损害', '心绞痛', '脑卒中', '颅脑损伤', '声带结节', '先天性肾畸形', '干眼症', '脂肪肝', '糖尿病性视网膜病变', '卵巢癌', '酒精性脂肪肝', '高血压性视网膜病变', '输尿管结石', '美尼尔氏症', '室性期前收缩', '房室传导阻滞', '视网膜损伤', '陶氏腔积液', '急性丙型肝炎', '二尖瓣狭窄', '听力异常', '膀胱结石', '肠息肉', '肺结核', '地中海贫血', '肾结石', '宫颈原位癌', '鼻腺体肥大', '良性胸腺瘤', '肾良性肿瘤', '心包炎', '肺外结核', '室颤', '疱疹', '游走心率', '溃疡性结肠炎', '卵圆孔未闭', '卵巢囊肿', '睡眠障碍', '肾盂肾炎', '甲状腺功能减退', '胆囊疾病', '动脉硬化性视网膜病变', '甲状腺功能亢进', '肺大疱', '房颤', '多囊肾', '腮腺炎', '恶性胸腺瘤', '肾囊肿', '肾盂积水', '假性乳房发育', '家族性高胆红素血症', '宫颈囊肿', '急性胰腺炎', '阵发性心动过速', '胆管结石', '新生儿室间隔缺损', '周围性面瘫', '静脉曲张', '紫癜', '胆道感染', '心脏溶栓或搭桥', '先天性白内障', '阴道炎', '脾破裂', '室性心动过速', '高血压', '多肌炎', '冠心病', '节段性肠炎', '预激综合征', '宫颈肿瘤'}

In [76]:
with open("./utils/KL_disease_n_2_name_map.json","w",encoding="utf-8") as f:
    json.dump(map_key_2_dise,f,ensure_ascii=False,indent=4)

In [67]:
map_key_2_dise["肾结"]

[('胆结石', 0.6666666666666667),
 ('肝内胆管结石', 0.33333333333333337),
 ('肾积水', 0.33333333333333337),
 ('肺结节', 0.33333333333333337),
 ('肾错构瘤', 0.25)]

In [77]:
#构建疾病及其相关关键词map, df来自中再疾病函数对照表
disease_n_2_list = {}
for idx,row in df_dise_2_keyword_kl.iterrows():
    disease_n = row["disease_n"].strip()
    disease_list = eval(row["disease_list"])
    # print(type(disease_list))
    try:
        if disease_n  not in disease_n_2_list and disease_n!="":
            disease_n_2_list[disease_n] = []
        disease_n_2_list[disease_n].extend(disease_list)
    except Exception as es:
        print(es)

In [78]:
with open("./utils/KL_disease_n_2_keyword.json","w",encoding="utf-8")as f:
    json.dump(disease_n_2_list,f,ensure_ascii=False,indent=4)

In [65]:
# 计算疾病相似度，并返回top_n最相近的疾病
def disease_similarity(input_dise,disease_n_2_list,top_n=3):
    disease_similarity_score = {}
    for k_dise,v_diseKey in disease_n_2_list.items():
        disease_similarity_score[k_dise] = max([normalized_similarity(input_dise,keyw) for keyw in v_diseKey])

    sorted_dict = sorted(disease_similarity_score.items(), key=lambda x: x[1], reverse=True)
    result =sorted_dict[:top_n]
    return result

In [66]:
query_dise = "双肾结晶"
results_query = disease_similarity(query_dise,disease_n_2_list)
print(results_query)
print(results_query[0][0])
df_dise_2_conc[df_dise_2_conc["disease_name"]==results_query[0][0]].head()

[('肾结石', 0.5), ('乳腺结节', 0.5), ('肾囊肿', 0.33333333333333337)]
肾结石

Empty DataFrame
Columns: [disease_name, file_name, conclusion]
Index: []

In [35]:
df = pd.read_csv("./规则引擎对比结果-评点数据.csv",keep_default_na=False)

In [38]:
gender_map = {2:"女性",1:"男"}
results_underwriting = []
recall_query = []
recall_time_use = []
for idx,row in df.iterrows():
    
    gender = gender_map.get(row["性别\n（1:男，2:女，0:未知）"],"未知")
    age = row["年龄"]
    diagnose = row["临床诊断（化验项、疾病等以下划线拼接）"]
    image_report = row["影像报告内容image_report"].replace('\\n',"")
    image_report = image_report.replace("\\",'').strip("\"").replace("\'","\"")
    basic_info = f"年龄:{age},性别:{gender},临床诊断:{diagnose},影像报告:{image_report}"
    print("病人基本信息",basic_info)
    print(image_report)
    # if image_report != "":
    #     image_report = json.loads(image_report)
    #     print(type(image_report))
    #     query = diagnose + image_report["des_dic"] + image_report["con_dic"]
    # else:
    #     query = diagnose    
    
    #召回方案：根据临床诊断召回相应核保结论
    query = diagnose
    
    
    try:
        s_time = time.time()
        #获得相似疾病name
        max_simi_dise_names = disease_similarity(query,disease_n_2_list)
        #获得相似疾病的结论
        recall_kbs = [ df_dise_2_conc[df_dise_2_conc["disease_name"]==max_simi_dis[0]]["conclusion"].tolist() for max_simi_dis in max_simi_dise_names]
        time_use = time.time() - s_time
        print("recall time use:",time_use)
        recall_time_use.append(time_use)
        ans_list = [recall_kb for recall_kb in recall_kbs if len(recall_kb)>0]
        ans_list = ans_list[0]

    except Exception as es:
        print(es)
        ans_list = []

    #构建prompt
    output_struct = {"重疾险": "延期", "防癌": "延期", "护理": "肾功能异常延期", "医疗险": "延期", "意外险": "肾功能异常延期"}
    prompt = """
            你是一个保险公司的专业核保老师，根据提供的病人基本信息和给定的核保结论返回最接近的核保结论。
            病人基本信息:{basic_info}
            核保结论:{ans_list}
            注意：
                1、核保结论的返回格式为:{output_struct}
                2、不要有其他信息说明
            """
    input_prompt = prompt.format(basic_info=basic_info,ans_list=ans_list,output_struct=output_struct)
    # print("input_prompt:",input_prompt)


    #大模型结论生成
    input = [{"role": "user", "content": input_prompt}]
    result = qa_base(input)

    results_underwriting.append(result)
    recall_query.append(ans_list)

病人基本信息 年龄:34,性别:女性,临床诊断:宫腔内稍高回声团,考虑子宫内膜息肉,影像报告:{"report_name": "", "des_dic": "经阴道三维超声检查：后位子宫  切面形态规则  体积不大  包膜完整  肌层回声分布均匀  未见明显肿块声像  内膜厚约8mm宫腔内可见一个大小约9x4mm稍高回声团，  边界清  CDFI:  其内未见明显血流信号。三维成像  ：双侧宫角可见显示  官腔形态未见异常。双侧附件区未见明显异常包块回声。子宫直肠窝未见游离液性暗区。", "con_dic": "宫腔内稍高回声团,  考虑子宫内膜息肉。双侧附件区未见明显异常包块回声。"}
{"report_name": "", "des_dic": "经阴道三维超声检查：后位子宫  切面形态规则  体积不大  包膜完整  肌层回声分布均匀  未见明显肿块声像  内膜厚约8mm宫腔内可见一个大小约9x4mm稍高回声团，  边界清  CDFI:  其内未见明显血流信号。三维成像  ：双侧宫角可见显示  官腔形态未见异常。双侧附件区未见明显异常包块回声。子宫直肠窝未见游离液性暗区。", "con_dic": "宫腔内稍高回声团,  考虑子宫内膜息肉。双侧附件区未见明显异常包块回声。"}
recall time use: 0.5981664657592773
病人基本信息 年龄:29,性别:女性,临床诊断:子宫肌瘤可能,影像报告:{"report_name": "", "des_dic": "【子宫】  【经阴道】子宫位置：  前位：  子宫大小：  长径  60mm,  左右径  65mm,  前后径  59mm;子宫形态：  不规则：  子宫回声：  不均匀：  肌层彩色血流星点状,内膜厚度12mm    宫颈长度  38mm子宫后壁突起中低回声区：  54*50*50mm", "con_dic": "子宫肌瘤可能。"}
{"report_name": "", "des_dic": "【子宫】  【经阴道】子宫位置：  前位：  子宫大小：  长径  60mm,  左右径  65mm,  前后径  59mm;子宫形态：  不规则：  子宫回声：  不均匀：  肌层彩色血流星点状,内膜厚度12mm    宫颈长度  38mm子宫后壁突起中低回声区：  54*50*50mm", "con_dic": "子宫肌瘤可能。"}
recall time use: 0.2224879264831543
病人基本信息 年龄:35,性别:男,临床诊断:双肾结石(沙粒样),影像报告:{"report_name": "", "des_dic": "双肾轮廓清晰。  切面形态大小正常：  表面光滑：  皮质回声正常  皮髓质分界清晰。  于双肾盏可见点状强回声  后伴浅声影。  双肾集合系统排列规则，  未见分离。  CDFI  未见明显异常血流信号。", "con_dic": "双肾结石（沙粒样）"}
{"report_name": "", "des_dic": "双肾轮廓清晰。  切面形态大小正常：  表面光滑：  皮质回声正常  皮髓质分界清晰。  于双肾盏可见点状强回声  后伴浅声影。  双肾集合系统排列规则，  未见分离。  CDFI  未见明显异常血流信号。", "con_dic": "双肾结石（沙粒样）"}
recall time use: 0.3172285556793213
list index out of range
病人基本信息 年龄:35,性别:男,临床诊断:脂肪肝（中度）,影像报告:{"report_name": "", "des_dic": "肝脏切面轮廊清晰，  右叶斜径约171mm  肝内回声前场增强细密，  后场稀疏衰减：  分布不均匀  肝内管道结构隐约可见  出肝光带模糊。  肝内胆管未见明显扩张  门静脉主干未见明显扩张  CDFI  未见明显异常血流信号。", "con_dic": "脂肪肝（中度）"}
{"report_name": "", "des_dic": "肝脏切面轮廊清晰，  右叶斜径约171mm  肝内回声前场增强细密，  后场稀疏衰减：  分布不均匀  肝内管道结构隐约可见  出肝光带模糊。  肝内胆管未见明显扩张  门静脉主干未见明显扩张  CDFI  未见明显异常血流信号。", "con_dic": "脂肪肝（中度）"}
recall time use: 0.25331783294677734
list index out of range
病人基本信息 年龄:34,性别:女性,临床诊断:双肾结石,影像报告:{"report_name": "", "des_dic": "双肾形态大小位置正常  包膜完整,  实质回声正常。  双肾可见强回声伴声影：  右侧大小约3×2mm，  左侧数个：  较大约3×2mm。CDF:  血流显示正常。", "con_dic": "双肾结石"}
{"report_name": "", "des_dic": "双肾形态大小位置正常  包膜完整,  实质回声正常。  双肾可见强回声伴声影：  右侧大小约3×2mm，  左侧数个：  较大约3×2mm。CDF:  血流显示正常。", "con_dic": "双肾结石"}
recall time use: 0.15745282173156738
list index out of range
病人基本信息 年龄:34,性别:女性,临床诊断:右侧甲状腺囊性结节,影像报告:{"report_name": "", "des_dic": "甲状腺右侧叶可见边界尚清晰的无回声区  大小约3×2mm。  CDFI:无回声区未见血流信号", "con_dic": "右侧甲状腺囊性结节"}
{"report_name": "", "des_dic": "甲状腺右侧叶可见边界尚清晰的无回声区  大小约3×2mm。  CDFI:无回声区未见血流信号", "con_dic": "右侧甲状腺囊性结节"}
recall time use: 0.3189084529876709
病人基本信息 年龄:34,性别:女性,临床诊断:胆囊息肉,影像报告:{"report_name": "", "des_dic": "胆囊形态大小正常  胆囊壁可见数枚稍高回声  较大约3×2mm后方无声影  不随体位改变而移动  胆汁充盈尚可：  胆总管内径正 常。", "con_dic": "胆囊息肉"}
{"report_name": "", "des_dic": "胆囊形态大小正常  胆囊壁可见数枚稍高回声  较大约3×2mm后方无声影  不随体位改变而移动  胆汁充盈尚可：  胆总管内径正 常。", "con_dic": "胆囊息肉"}
recall time use: 0.15743470191955566
病人基本信息 年龄:45,性别:男,临床诊断:右侧甲状腺下极下方囊性灶，  考虑甲状旁腺来源可能,影像报告:{"report_name": "", "des_dic": "双侧甲状腺外形正常：  包膜光整,  内部回声均匀,左侧实质内未见明显异常结节回声,  CDFI示甲状腺实质血供正常。  弹性成像示甲状腺实质硬度：  质中。右侧甲状腺下极下方可见一个无回声，  大小约25×17mm  形状呈椭圆形,  内部回声尚可,  边界尚清,  内部未见明显点状强回声，CDFI：  未见明显异常血流信号。左侧甲状旁腺区未见明显占位性病变。双侧颈部未见明显异常肿大淋巴结。", "con_dic": "右侧甲状腺下极下方囊性灶，  考虑甲状旁腺来源可能，  请结合临床双侧甲状旁腺区未见明显异常双侧颈部未见明显异常淋巴结"}
{"report_name": "", "des_dic": "双侧甲状腺外形正常：  包膜光整,  内部回声均匀,左侧实质内未见明显异常结节回声,  CDFI示甲状腺实质血供正常。  弹性成像示甲状腺实质硬度：  质中。右侧甲状腺下极下方可见一个无回声，  大小约25×17mm  形状呈椭圆形,  内部回声尚可,  边界尚清,  内部未见明显点状强回声，CDFI：  未见明显异常血流信号。左侧甲状旁腺区未见明显占位性病变。双侧颈部未见明显异常肿大淋巴结。", "con_dic": "右侧甲状腺下极下方囊性灶，  考虑甲状旁腺来源可能，  请结合临床双侧甲状旁腺区未见明显异常双侧颈部未见明显异常淋巴结"}
recall time use: 0.8382506370544434
list index out of range
病人基本信息 年龄:36,性别:男,临床诊断:肝血管瘤,影像报告:{"report_name": "", "des_dic": "肝脏：  大小形声正常。  包膜光滑连续：  肝右叶可见无回声：  大小约5mm*5mm 形态规则，边界清：  肝内可见稍高回声  大小约7mm*7mm，边界清  形态规则 内部回声欠均匀，CDFI 其内未见明显血流信号", "con_dic": "肝囊肿肝血管瘤"}
{"report_name": "", "des_dic": "肝脏：  大小形声正常。  包膜光滑连续：  肝右叶可见无回声：  大小约5mm*5mm 形态规则，边界清：  肝内可见稍高回声  大小约7mm*7mm，边界清  形态规则 内部回声欠均匀，CDFI 其内未见明显血流信号", "con_dic": "肝囊肿肝血管瘤"}
recall time use: 0.15625381469726562
病人基本信息 年龄:36,性别:男,临床诊断:肝囊肿,影像报告:{"report_name": "", "des_dic": "肝脏：  大小形声正常。  包膜光滑连续：  肝右叶可见无回声：  大小约5mm*5mm 形态规则，边界清：  肝内可见稍高回声  大小约7mm*7mm，边界清  形态规则 内部回声欠均匀，CDFI 其内未见明显血流信号", "con_dic": "肝囊肿肝血管瘤"}
{"report_name": "", "des_dic": "肝脏：  大小形声正常。  包膜光滑连续：  肝右叶可见无回声：  大小约5mm*5mm 形态规则，边界清：  肝内可见稍高回声  大小约7mm*7mm，边界清  形态规则 内部回声欠均匀，CDFI 其内未见明显血流信号", "con_dic": "肝囊肿肝血管瘤"}
recall time use: 0.12341570854187012
病人基本信息 年龄:36,性别:男,临床诊断:双肺上叶微小结节，多为增殖灶,影像报告:{"report_name": "", "des_dic": "两侧胸廓对称。肺窗示双肺上叶见微小结节灶。直径约2mm，边界清。左肺极少许纤维条索影。两肺门不大。纵隔窗示心影及大血管形态正常，纵隔内未见肿块及明显肿大淋巴结。无胸腔积液及胸膜增厚", "con_dic": "双肺上叶微小结节左肺纤维灶"}
{"report_name": "", "des_dic": "两侧胸廓对称。肺窗示双肺上叶见微小结节灶。直径约2mm，边界清。左肺极少许纤维条索影。两肺门不大。纵隔窗示心影及大血管形态正常，纵隔内未见肿块及明显肿大淋巴结。无胸腔积液及胸膜增厚", "con_dic": "双肺上叶微小结节左肺纤维灶"}
recall time use: 0.4723665714263916
病人基本信息 年龄:36,性别:男,临床诊断:双肾结晶,影像报告:{"report_name": "", "des_dic": "肾脏：  双肾大小形态正常，轮廓光滑规整，双肾肾窦内可见点状强回声。后无明显声影。集合系统无分离", "con_dic": "双肾结晶"}
{"report_name": "", "des_dic": "肾脏：  双肾大小形态正常，轮廓光滑规整，双肾肾窦内可见点状强回声。后无明显声影。集合系统无分离", "con_dic": "双肾结晶"}
recall time use: 0.15515971183776855
list index out of range
病人基本信息 年龄:26,性别:男,临床诊断:脂肪肝,影像报告:{"report_name": "", "des_dic": "肝脏体积增大  形态饱满,  肝实质回声增强  光点细定。  远程回声衰减  肝内血管网络欠清晰  门静脉内径正常。  左右肝内胆管未见扩张", "con_dic": "脂肪肝"}
{"report_name": "", "des_dic": "肝脏体积增大  形态饱满,  肝实质回声增强  光点细定。  远程回声衰减  肝内血管网络欠清晰  门静脉内径正常。  左右肝内胆管未见扩张", "con_dic": "脂肪肝"}
recall time use: 0.12222909927368164
list index out of range
病人基本信息 年龄:35,性别:女性,临床诊断:右侧乳腺结节待查,影像报告:

recall time use: 0.28337574005126953
list index out of range
病人基本信息 年龄:38,性别:女性,临床诊断:右侧乳腺结节待查,影像报告:{"report_name": "", "des_dic": "双侧乳腺腺体致密内部回声增强，  结构紊乱  分布不均腺管未见明显扩张,  CDFI：未见明显异常血流信号  右侧乳腺乳头下方可见边界清晰的低回声结节  大小约5×3mm  CDFI:血流未见明显异常", "con_dic": "乳腺增生右侧乳腺结节待查"}
{"report_name": "", "des_dic": "双侧乳腺腺体致密内部回声增强，  结构紊乱  分布不均腺管未见明显扩张,  CDFI：未见明显异常血流信号  右侧乳腺乳头下方可见边界清晰的低回声结节  大小约5×3mm  CDFI:血流未见明显异常", "con_dic": "乳腺增生右侧乳腺结节待查"}
recall time use: 0.29327940940856934
list index out of range
病人基本信息 年龄:38,性别:女性,临床诊断:双侧甲状腺结节,影像报告:{"report_name": "", "des_dic": "甲状腺双侧叶见边界尚清晰的低回声结节  较大位于右侧  大小约5×3mm。CDFI:  血流未见明显异常", "con_dic": "双侧甲状腺结节"}
{"report_name": "", "des_dic": "甲状腺双侧叶见边界尚清晰的低回声结节  较大位于右侧  大小约5×3mm。CDFI:  血流未见明显异常", "con_dic": "双侧甲状腺结节"}
recall time use: 0.26634669303894043
病人基本信息 年龄:38,性别:女性,临床诊断:多发性胆囊息肉,影像报告:{"report_name": "", "des_dic": "多发性胆囊息肉  最大约4×4mm", "con_dic": "多发性胆囊息肉"}
{"report_name": "", "des_dic": "多发性胆囊息肉  最大约4×4mm", "con_dic": "多发性胆囊息肉"}
recall time use: 0.2558772563934326
病人基本信息 年龄:38,性别:女性,临床诊断:左肺上叶前段磨玻璃影,影像报告:{"report_name": "", "des_dic": "胸廓对称：  纵隔居中。右肺下叶局部少许点片模糊影。  左肺上叶（201-22）见磨玻璃影,  大小约为9mm×7mm气管及诸叶、段支气管尚通畅心脏无明显增大：  大血管走行如常。纵隔未见明确增大淋巴结。双侧胸腔未见积液征象。", "con_dic": "左肺上叶前段磨玻璃影"}
{"report_name": "", "des_dic": "胸廓对称：  纵隔居中。右肺下叶局部少许点片模糊影。  左肺上叶（201-22）见磨玻璃影,  大小约为9mm×7mm气管及诸叶、段支气管尚通畅心脏无明显增大：  大血管走行如常。纵隔未见明确增大淋巴结。双侧胸腔未见积液征象。", "con_dic": "左肺上叶前段磨玻璃影"}
recall time use: 0.3536524772644043
list index out of range
病人基本信息 年龄:34,性别:男,临床诊断:甲状腺右叶囊肿(ACRTI-RADS1类),影像报告:{"report_name": "", "des_dic": "甲状腺形态大小正常  峡部厚度正常  包膜完整,  实质回声增粗左侧叶上极内可见一个等回声区，  大小约11.  1mm×6.9mm  边界清  形态规则：  内回声不均匀  其内可见无回声,  CDFI  周边及内部未见明显异常血流信号右侧叶上极内可见一个无回声区，  大小约1.8mm×1.7mm  边界清  内透声可：  后方回声增强：  CDFI  未见异常血流信号.峡部未见明显占位性病变", "con_dic": "甲状腺左叶结节（ACR  TI-RADS3类)甲状腺右叶囊肿（ACR  TI-RADS  1类）"}
{"report_name": "", "des_dic": "甲状腺形态大小正常  峡部厚度正常  包膜完整,  实质回声增粗左侧叶上极内可见一个等回声区，  大小约11.  1mm×6.9mm  边界清  形态规则：  内回声不均匀  其内可见无回声,  CDFI  周边及内部未见明显异常血流信号右侧叶上极内可见一个无回声区，  大小约1.8mm×1.7mm  边界清  内透声可：  后方回声增强：  CDFI  未见异常血流信号.峡部未见明显占位性病变", "con_dic": "甲状腺左叶结节（ACR  TI-RADS3类)甲状腺右叶囊肿（ACR  TI-RADS  1类）"}
recall time use: 0.700371503829956
list index out of range
病人基本信息 年龄:34,性别:男,临床诊断:甲状腺左叶结节(ACRTI-RADS3类),影像报告:{"report_name": "", "des_dic": "甲状腺形态大小正常  峡部厚度正常  包膜完整,  实质回声增粗左侧叶上极内可见一个等回声区，  大小约11.  1mm×6.9mm  边界清  形态规则：  内回声不均匀  其内可见无回声,  CDFI  周边及内部未见明显异常血流信号右侧叶上极内可见一个无回声区，  大小约1.8mm×1.7mm  边界清  内透声可：  后方回声增强：  CDFI  未见异常血流信号.峡部未见明显占位性病变", "con_dic": "甲状腺左叶结节（ACR  TI-RADS3类)甲状腺右叶囊肿（ACR  TI-RADS  1类）"}
{"report_name": "", "des_dic": "甲状腺形态大小正常  峡部厚度正常  包膜完整,  实质回声增粗左侧叶上极内可见一个等回声区，  大小约11.  1mm×6.9mm  边界清  形态规则：  内回声不均匀  其内可见无回声,  CDFI  周边及内部未见明显异常血流信号右侧叶上极内可见一个无回声区，  大小约1.8mm×1.7mm  边界清  内透声可：  后方回声增强：  CDFI  未见异常血流信号.峡部未见明显占位性病变", "con_dic": "甲状腺左叶结节（ACR  TI-RADS3类)甲状腺右叶囊肿（ACR  TI-RADS  1类）"}
recall time use: 0.6915552616119385
病人基本信息 年龄:34,性别:男,临床诊断:肝内胆管结石(多发),影像报告:{"report_name": "", "des_dic": "肝脏形态大小正常：  包膜光滑,  管道结构清晰,  肝左内叶可见多个强光点  大者约4mm×3mm  后伴淡声影  其旁可见裂隙样无回声  未见异常血流信号", "con_dic": "肝内胆管结石（多发）"}
{"report_name": "", "des_dic": "肝脏形态大小正常：  包膜光滑,  管道结构清晰,  肝左内叶可见多个强光点  大者约4mm×3mm  后伴淡声影  其旁可见裂隙样无回声  未见异常血流信号", "con_dic": "肝内胆管结石（多发）"}
recall time use: 0.3493649959564209
病人基本信息 年龄:29,性别:女性,临床诊断:两肺多发小结节,影像报告:{"report_name": "", "des_dic": "两肺纹理增多  双肺见多发结节  较大者位于右肺下叶外基底段（SN4  Im185),  为实性结节,  大小约为5×4mm;  余两肺内未见明显异常。  所见各支气管腔通畅  肺门未见增大,  纵隔未见肿大淋巴结  心脏形态及密度未见明显异常  两侧胸腔未见明显积液胸膜未见明显增厚", "con_dic": "两肺多发小结节"}
{"report_name": "", "des_dic": "两肺纹理增多  双肺见多发结节  较大者位于右肺下叶外基底段（SN4  Im185),  为实性结节,  大小约为5×4mm;  余两肺内未见明显异常。  所见各支气管腔通畅  肺门未见增大,  纵隔未见肿大淋巴结  心脏形态及密度未见明显异常  两侧胸腔未见明显积液胸膜未见明显增厚", "con_dic": "两肺多发小结节"}
recall time use: 0.25563740730285645
list index out of range
病人基本信息 年龄:29,性别:女性,临床诊断:右乳囊性结节拟US-BI-RADS2类,影像报告:{"report_name": "", "des_dic": "双侧乳房皮下脂肪厚度基本正常，  腺体厚正常范围,  乳腺组织回声尚均匀  可见散在条索状、斑块状回声减低区  CDFI乳腺内未见明显异常血流信号右乳9点钟方向见一枚囊性结节  大小约3mmx2mm,  水平位生长,  边缘光整,  形态规则,  后方回声增强。  CDFI显示AdlerO级双侧乳腺乳头后方均见乳腺导管增宽，  较宽处均约2mm双侧腋窝未探及明显异常肿大淋巴结。", "con_dic": "右乳囊性结节  拟US-BI-RADS2类双乳乳腺扩张"}
{"report_name": "", "des_dic": "双侧乳房皮下脂肪厚度基本正常，  腺体厚正常范围,  乳腺组织回声尚均匀  可见散在条索状、斑块状回声减低区  CDFI乳腺内未见明显异常血流信号右乳9点钟方向见一枚囊性结节  大小约3mmx2mm,  水平位生长,  边缘光整,  形态规则,  后方回声增强。  CDFI显示AdlerO级双侧乳腺乳头后方均见乳腺导管增宽，  较宽处均约2mm双侧腋窝未探及明显异常肿大淋巴结。", "con_dic": "右乳囊性结节  拟US-BI-RADS2类双乳乳腺扩张"}
recall time use: 0.6338415145874023
list index out of range
病人基本信息 年龄:30,性别:女性,临床诊断:甲状腺右叶结节,影像报告:{"report_name": "", "des_dic": "甲状腺：  大小形态正常。  右叶内见数个结节,  最大者大小约16mmX9mm，  边界尚清,  形态尚规则,  CDFI:  周边见血流环抱。  余甲状腺轮廓尚清  形态规则,  内部回声粗,  分布不均匀。CDFI:  未见明显异常双侧甲状旁腺区未见明显异常占位回声。双侧颈部见多个低回声区，  其内见高回声,  最大者大小约20mmX9mm  边界尚清,  形态尚规则。  CDFI:  未见明显异常", "con_dic": "甲状腺右叶结节  （TI-RADS3级）甲状腺质地不均"}
{"report_name": "", "des_dic": "甲状腺：  大小形态正常。  右叶内见数个结节,  最大者大小约16mmX9mm，  边界尚清,  形态尚规则,  CDFI:  周边见血流环抱。  余甲状腺轮廓尚清  形态规则,  内部回声粗,  分布不均匀。CDFI:  未见明显异常双侧甲状旁腺区未见明显异常占位回声。双侧颈部见多个低回声区，  其内见高回声,  最大者大小约20mmX9mm  边界尚清,  形态尚规则。  CDFI:  未见明显异常", "con_dic": "甲状腺右叶结节  （TI-RADS3级）甲状腺质地不均"}
recall time use: 0.25632238388061523
病人基本信息 年龄:31,性别:男,临床诊断:右肺微小结节,影像报告:{"report_name": "", "des_dic": "双侧胸廓对称,  纵隔居中,  右肺见微小结节影  直径约1-2mm  气管及各分支气管通畅,  双肺门结构正常,  纵隔内未见异常肿大淋巴结，  双侧胸膜光滑,  心影大小、形态正常。", "con_dic": "右肺微小结节"}
{"report_name": "", "des_dic": "双侧胸廓对称,  纵隔居中,  右肺见微小结节影  直径约1-2mm  气管及各分支气管通畅,  双肺门结构正常,  纵隔内未见异常肿大淋巴结，  双侧胸膜光滑,  心影大小、形态正常。", "con_dic": "右肺微小结节"}
recall time use: 0.22202324867248535
list index out of range
病人基本信息 年龄:31,性别:男,临床诊断:轻度脂肪肝,影像报告:{"report_name": "", "des_dic": "肝脏大小正常  回声轻度增强  细密  分布均匀  远场回声衰减不明显,  可见肝内管道和膜肌边界", "con_dic": "轻度脂肪肝"}
{"report_name": "", "des_dic": "肝脏大小正常  回声轻度增强  细密  分布均匀  远场回声衰减不明显,  可见肝内管道和膜肌边界", "con_dic": "轻度脂肪肝"}
recall time use: 0.1883542537689209
list index out of range
病人基本信息 年龄:31,性别:男,临床诊断:双肾结晶,影像报告:{"report_name": "", "des_dic": "双肾大小位置正常  包膜光滑  实质厚度正常,  双肾内均可见数个偏强回声", "con_dic": "双肾结晶"}
{"report_name": "", "des_dic": "双肾大小位置正常  包膜光滑  实质厚度正常,  双肾内均可见数个偏强回声", "con_dic": "双肾结晶"}
recall time use: 0.15717077255249023
list index out of range
病人基本信息 年龄:31,性别:男,临床诊断:窦性心律不齐,影像报告:

recall time use: 0.21904945373535156
list index out of range
病人基本信息 年龄:31,性别:女性,临床诊断:桥本氏甲状腺炎,影像报告:

recall time use: 0.2556283473968506
病人基本信息 年龄:31,性别:女性,临床诊断:颈椎病,影像报告:

recall time use: 0.12345051765441895
病人基本信息 年龄:31,性别:女性,临床诊断:双肾结晶,影像报告:

recall time use: 0.15672707557678223
list index out of range
病人基本信息 年龄:31,性别:女性,临床诊断:肺动脉少量反流,影像报告:

recall time use: 0.2536005973815918
list index out of range

In [39]:
sum(recall_time_use)/len(recall_time_use)

0.3065094128251076

In [42]:
df["RAG核保结论"] = results_underwriting
df["recall_query"] = recall_query
df.to_csv("./results_edit_distance/核保结论_规则引擎_vs_RAG_editDistanceSearch.csv",index=False)

In [48]:
len_get_recall = len([rec_res for rec_res in recall_query if len(rec_res)!=0])
print(len_get_recall)
print(f"召回率：{round(len_get_recall/len(recall_query)*100,2)}%")

14
召回率：43.75%

In [4]:
# df_full = pd.read_csv("./核保结论_规则引擎_vs_RAG_FullTextSearch.csv")
# df_full = pd.read_csv("./核保结论_规则引擎_vs_RAG_SemanticSearch.csv")
# df_full = pd.read_csv("./核保结论_规则引擎_vs_RAG_HybridSearch.csv")
df_full = pd.read_csv("./results_edit_distance/核保结论_规则引擎_vs_RAG_editDistanceSearch.csv")


# recall_query = df_full["recall_query"].tolist()
# len_get_recall = len([rec_res for rec_res in recall_query if len(eval(rec_res))!=0])
# print(len_get_recall)
# print(f"召回率：{round(len_get_recall/len(recall_query)*100,2)}%")
bad_dise = []
for idx,row in df_full.iterrows():
    if len(eval(row["recall_query"])) == 0:
        bad_dise.append(row["临床诊断（化验项、疾病等以下划线拼接）"])
print(len(bad_dise))
print(bad_dise)

18
['双肾结石(沙粒样)', '脂肪肝（中度）', '双肾结石', '右侧甲状腺下极下方囊性灶，  考虑甲状旁腺来源可能', '双肾结晶', '脂肪肝', '右侧乳腺结节待查', '右侧乳腺结节待查', '左肺上叶前段磨玻璃影', '甲状腺右叶囊肿(ACRTI-RADS1类)', '两肺多发小结节', '右乳囊性结节拟US-BI-RADS2类', '右肺微小结节', '轻度脂肪肝', '双肾结晶', '窦性心律不齐', '双肾结晶', '肺动脉少量反流']

# check 疾病对照表

In [6]:
print(len(disease_n_2_list))

NameError: name 'disease_n_2_list' is not defined

In [ ]:
and_words = set(disease_n_2_list.keys()) & set(df_dise_2_conc["disease_name"].tolist())
print(len(and_words))

111

In [6]:
df_one_dise = df_dise_2_conc[df_dise_2_conc["disease_name"]=="银行"]
df_one_dise["conclusion"].tolist()

[]